export const ActionTypes = {
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    CHANGE_EDIT_STATE:"CHANGE_EDIT_STATE",
    GET_ERROR_LOGIN:"GET_ERROR_LOGIN",
    GET_USER_LOGIN:"GET_USER_LOGIN",
    CHANGE_EDIT_STATE_LOGIN:"CHANGE_EDIT_STATE_LOGIN",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ITEM:"REMOVE_ITEM",
    DEMO_ADD_TO_CART:"DEMO_ADD_TO_CART",
    CHANGE_STATE_PAYMENT:"CHANGE_STATE_PAYMENT"
}